---
RecipeFormatVersion: '2020-01-25'
ComponentName: co.mgh.ShadowManager
ComponentDescription: AWS Greengrass Shadow Manager
ComponentPublisher: AWS
ComponentVersion: '0.0.0'
ComponentType: 'aws.greengrass.plugin'
Manifests:
  - Platform:
      os: all
    Artifacts:
      - URI: s3://$S3_BUCKET/co.mgh.ShadowManager.jar
